### ISSUE TITLE
Immediate Crash/Reboot when autoplace > 0 on 6.1.x kernel

### ISSUE THREAD

**Issue by themicknugget** [LINBIT/drbd#57]
Hello,

I'm using Talos Linux, and trying to use DRBD for the piraeus operator. When autoplace/replicas is 1, there's no issue, but once I set it to 3 and try to provision a pvc against it, the node the pvc's pod is scheduled on reboots.

I initially opened an issue with Talos Linux, but they referred me to open an issue here as it appears to be related to the module compiled against 6.1 kernel.

 I have attached a talos dmesg log. I've attached the "talos dmesg" kernel log, and at the time of the crash there's no additional kernel panic/messages on the console.

Thank you!
[drbd-crash.log](https://github.com/LINBIT/drbd/files/11478831/drbd-crash.log)

**Comment by chrboe** [comment]
Hello,

this sounds similar to an issue other users are experiencing with newer kernels. We cannot yet reproduce this issue on any of our test systems.

Can you share a bit of information about your environment? What hardware are you using, what's your backing device (LVM, ZFS, raw?), etc.

**Comment by lidstah** [comment]
Hello,

I have the same problem on a talos linux 1.4.4 cluster, hosted on a proxmox (7.3.4) cluster. Workers run on a ryzen 4800U, with the "host" CPU proxmox parameter. The workers' disks are hosted on a SSD, lvm-thin.

The workers are labelled with a `piraeus-test.dev/storage: "yes"` label, and machineconfigs are patched like this:

```
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/drbd:9.2.2-v1.4.4
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
```

The LinstorCluster object is defined like this:

```
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  nodeSelector:
    piraeus-test.dev/storage: "yes"
```
Satellite configuration is patched according to piraeus talos linux documentation, and defined like this:

```
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  storagePools:
    - name: pool1
      fileThinPool:
        directory: /var/lib/piraeus-datastore/pool1
```
Finally, the "offending" storageClass is defined like this:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-storage
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagePool: pool1
  autoPlace: "2"
```
Once a PVC is attached to a pod, the node crashes and reboot. If I then delete the deployment, the PVC stays in bounded state to its PV, and using the linstor-controller console:

```LINSTOR ==> vd list
╭───────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName                             ┊ VolumeNr ┊ VolumeMinor ┊ Size  ┊ Gross ┊ State ┊
╞═══════════════════════════════════════════════════════════════════════════════════════════╡
┊ pvc-60a3dcd4-5cf1-454b-8ee8-f92d804661a6 ┊ 0        ┊ 1000        ┊ 5 GiB ┊       ┊ ok    ┊
╰───────────────────────────────────────────────────────────────────────────────────────────╯

LINSTOR ==> v l
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node          ┊ Resource                                 ┊ StoragePool          ┊ VolNr ┊ MinorNr ┊ DeviceName    ┊ Allocated ┊ InUse  ┊      State ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ talos-worker1 ┊ pvc-60a3dcd4-5cf1-454b-8ee8-f92d804661a6 ┊ DfltDisklessStorPool ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊           ┊ Unused ┊ TieBreaker ┊
┊ talos-worker5 ┊ pvc-60a3dcd4-5cf1-454b-8ee8-f92d804661a6 ┊ pool1                ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊  3.75 MiB ┊ Unused ┊   UpToDate ┊
┊ talos-worker6 ┊ pvc-60a3dcd4-5cf1-454b-8ee8-f92d804661a6 ┊ pool1                ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊  3.74 MiB ┊ Unused ┊   UpToDate ┊
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
shows that the volumes are created accordingly to the autoPlace parameter. Behavior is  the same with autoPlace: "3", except that all volumes are created in pool1 (my two-cents guess is that the DfltDisklessStorPool volume above is created for quorum considerations).

Hoping it'll help,

Best regards,
